### ISSUE TITLE
Getting 'Error: unable to read keypair file'

### ISSUE THREAD

**Issue by metaproph3t** [mrgnlabs/anchor-test-action#4]
Using default code generated by 'anchor init.' This is action run: [log](https://github.com/0xBrahma/futarchy/runs/7508717763?check_suite_focus=true).

**Comment by metaproph3t** [comment]
This is the action file:
```
name: anchor-test
on: [push]
jobs:
  run-anchor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Anchor Test
        uses: mrgnlabs/anchor-test-action@v0.4
        with:
          args: ""
          workspace_dir: "."
```
